---
kind: Ingress
metadata:
  name: home-assistant
  labels:
    app: home-assistant
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    kubernetes.io/tls-acme: "true"
    kubesailEditorUid: 30e719db-e91b-4f67-95eb-3bbb7a0c8f16
    nginx.ingress.kubernetes.io/proxy-body-size: 500m
    kubesail.com/template: erulabs/home-assistant:v25
apiVersion: networking.k8s.io/v1
spec:
  tls:
    - hosts:
        - home-assistant.{{ CLUSTER_ADDRESS }}
  rules:
    - host: home-assistant.{{ CLUSTER_ADDRESS }}
      http:
        paths:
          - pathType: ImplementationSpecific
            backend:
              service:
                name: home-assistant
                port:
                  name: http
