---
kind: Service
metadata:
  name: home-assistant
  labels:
    app: home-assistant
  annotations:
    kubesailEditorUid: e5836c75-9b16-41bb-9319-456335883f71
    kubesail.com/template: erulabs/home-assistant:v25
apiVersion: v1
spec:
  selector:
    app: home-assistant
  ports:
    - name: http
      port: 8123
      protocol: TCP
      targetPort: http
