apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  namespace: argo-cd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-cd
  project: default
  source:
    path: argocd-install-master/charts/argo-cd/
    repoURL: https://github.com/jakebuckeye1919/rpi4k3cluster/argocd-install-master.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
