apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: prometheus
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    chart: prometheus
    helm:
      values: |
        pushgateway:
          enabled: false
    repoURL: https://github.com/jakebuckeye1919/rpi4k3cluster/argocd-install-master.git
    targetRevision: 15.6.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
